apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  name: monitoring-hoteis
  namespace: monitoring-hoteis
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: 260584439167.dkr.ecr.sa-east-1.amazonaws.com/monitoringhotel:__TAG__
            imagePullPolicy: IfNotPresent
            name: monitoring-hoteis
            resources:
              limits:
                cpu: "2"
                memory: 2Gi
              requests:
                cpu: "1"
                memory: 1Gi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  schedule: '* * * * *'
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 3
  suspend: false